import { db } from '@/lib/db';
import { NextRequest, NextResponse } from 'next/server';

/**
 * POST /api/datasources/fix-stock-dispo
 * GET  /api/datasources/fix-stock-dispo
 *
 * ━━━ RETROACTIVE FIX: Cascade Stock → Disponibilité ━━━
 * Scans all rows across all DataSources (or a specific one) and fixes
 * mismatched stock/disponibilité states.
 *
 * Default rules (always applied):
 * - stock > 0 + __disponibilite__ = 'false' → set to 'true' (Disponible)
 *
 * With ?fix_sur_commande=true (explicit opt-in):
 * - stock = 0 + __disponibilite__ = 'true' → set to 'false' (Épuisé)
 *   This removes "Sur commande" states that were auto-generated by the
 *   import bug. Admin can then manually re-enable Sur commande if desired.
 *
 * GET endpoint allows triggering without authentication (one-time migration fix).
 */
export async function GET(req: NextRequest) {
  return fixStockDispo(req);
}

export async function POST(req: NextRequest) {
  return fixStockDispo(req);
}

async function fixStockDispo(req: NextRequest) {
  try {
    const body = req.method === 'POST' ? await req.json().catch(() => ({})) : {};
    const url = new URL(req.url);
    const dataSourceId = body.dataSourceId || url.searchParams.get('dataSourceId') || undefined;
    const fixSurCommande = body.fix_sur_commande === true || url.searchParams.get('fix_sur_commande') === 'true';

    // Load rows — either for a specific DataSource or all
    const where = dataSourceId ? { dataSourceId } : {};
    const rows = await db.row.findMany({ where });

    console.log(`🔧 RETROACTIVE FIX: Scanning ${rows.length} rows for stock/disponibilité mismatch${dataSourceId ? ` (DataSource: ${dataSourceId})` : ' (ALL)'}${fixSurCommande ? ' [WITH fix_sur_commande=true]' : ''}`);

    let fixedToDisponible = 0;
    let fixedToEpuise = 0;
    let surCommandePreserved = 0;

    for (const row of rows) {
      const data = row.data as Record<string, unknown>;
      const stockVal = typeof data.__stock__ === 'number'
        ? data.__stock__
        : parseInt(String(data.__stock__ ?? '0')) || 0;

      const dispoVal = String(data.__disponibilite__ ?? 'false');

      // Fix 1: stock > 0 but Disponibilité = OFF (Épuisé) → Disponible
      if (stockVal > 0 && dispoVal === 'false') {
        const updatedData = { ...data, __disponibilite__: 'true' };
        await db.row.update({
          where: { id: row.id },
          data: { data: updatedData },
        });
        fixedToDisponible++;
        continue;
      }

      // Fix 2 (opt-in): stock = 0 + Disponibilité = ON → Épuisé
      // Only applied when fix_sur_commande=true is passed
      // "Sur commande" should NEVER be auto-generated by import — it's purely manual.
      if (stockVal === 0 && dispoVal === 'true') {
        if (fixSurCommande) {
          const updatedData = { ...data, __disponibilite__: 'false' };
          await db.row.update({
            where: { id: row.id },
            data: { data: updatedData },
          });
          fixedToEpuise++;
        } else {
          surCommandePreserved++;
        }
      }
    }

    console.log(`✅ RETROACTIVE FIX COMPLETE: ${fixedToDisponible} stock>0→Disponible, ${fixedToEpuise} stock=0→Épuise${fixSurCommande ? '' : `, ${surCommandePreserved} Sur commande preserved (use fix_sur_commande=true to fix)`}`);

    return NextResponse.json({
      data: {
        totalRows: rows.length,
        fixedToDisponible,
        fixedToEpuise,
        surCommandePreserved,
      },
      error: null,
    });
  } catch (error) {
    console.error('❌ RETROACTIVE FIX error:', error);
    return NextResponse.json(
      { data: null, error: 'Failed to fix stock/disponibilité mismatch' },
      { status: 500 }
    );
  }
}
